name: Uptime Monitoring

on:
  schedule:
    - cron: '*/15 * * * *' # Runs every 15 minutes
  workflow_dispatch:

jobs:
  check-uptime:
    runs-on: ubuntu-latest

    steps:
    - name: Check API health
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.API_URL }}/api/version)
        if [ $response -ne 200 ]; then
          echo "Health check failed with status code $response"
          exit 1
        else
          echo "Health check passed with status code $response"
        fi